# Włączenie podsystemu czujników i magistrali I2C
CONFIG_I2C=y
CONFIG_SENSOR=y

# Włączenie wbudowanego sterownika dla BME280
CONFIG_BME280=y

# Opcjonalne, ale BARDZO ZALECANE do odczytu danych:
# Włączenie logów (żeby widzieć wyniki w terminalu)
CONFIG_LOG=y
# Włączenie obsługi liczb zmiennoprzecinkowych (ułamków) w funkcjach typu printk/printf. 
# Bez tego nie wypiszesz temperatury np. "23.5 C", system wyrzuci błąd lub puste miejsce.
CONFIG_CBPRINTF_FP_SUPPORT=y